### ISSUE TITLE
Citra/yuzu-related Tracking Issue

### ISSUE THREAD

**Issue by merryhime** [merryhime/dynarmic#286]
Keeping track of feature requests:

 - [x] ~~softfloat impl~~ (in progress)
 - [x] global exclusive monitor
 - [x] single-stepping
 - [x] execution breakpoints
 - [x] linux/perf support (/tmp/perf-PID.map)
 - [ ] microprofile within the recompiler
