### ISSUE TITLE
TODO: Exclusive memory

### ISSUE THREAD

**Issue by merryhime** [merryhime/dynarmic#527]
- [ ] Use page-tables instead of callbacks
- [ ] Inline locking into emitted assembly
- [ ] Don't use VAddr to key the monitor, instead use the underlying memory address instead as a poor-man's substitute for PAddr.
  - [ ] Consider providing a mode for fastmem-only users.
